name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest

        env:
            MONGODB_HOST: localhost
            MONGODB_NAME: test
            CRYPTO_ITERATIONS: 1
            CRYPTO_LENGTH: 128
            CRYPTO_DIGEST: sha512
            SECRET: somesecret

        steps:
            - uses: actions/checkout@v2

            - name: Install packages
              run: npm install

            - name: Prepare MongoDB
              uses: supercharge/mongodb-github-action@1.3.0

            - name: Testing
              run: npm t
